/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(rootProject.libs.bundles.implementation)
    implementation(project(":utilities"))
    
    // Lombok annotation processing
    compileOnly(rootProject.libs.lombok)
    annotationProcessor(rootProject.libs.lombok)
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

springBoot {
    mainClass = "org.example.app.App"
}
