/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    // Apply Spring Boot plugin for Spring Boot application support
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}
